apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 30m
  timeout: 60s
  url: https://github.com/fluxcd/flux2
  ref:
    tag: v2.0.0-rc.5